some small ui tweaks
transfem-org/Sharkey pull request #119
Opened 2023-10-30 12:44 UTC by ShittyKopper

* rounded timeline corners when "Show a gap between posts on the timeline" is disabled
* show a pointer cursor when hovering over clickable parts of notes when "Click to open notes" is enabled
* hide status indicators when they're in an "unknown" state
* add more shadows

<details>
<summary>before</summary>

![Screenshot 2023-10-30 at 15-19-55 @kopper](https://github.com/transfem-org/Sharkey/assets/106974765/933ad4d4-a5ec-423b-97a6-1e9d7f9b775d)
</details>

<details>
<summary>after</summary>

![Screenshot 2023-10-30 at 15-18-42 @kopper](https://github.com/transfem-org/Sharkey/assets/106974765/a2692382-001c-419c-a157-7be164c21e4e)
</details>

there are three parts of this pr i'm not too sure on:

* i directly copied the ._shadow helper's box-shadow definition for consistency, but i'm not entirely sure if the size of those shadows fit the ui. it may make sense to play with the individual shadow sizes
    * imo it's still better than having no separation between the elements and the background
* 4fcd47bf087480b3ee731eff4d24f5de2b40fe29 feels a bit too "fragile" as i just apply a shadow to all panel elements no matter what. so far there is only one obvious exception i could find that needed reverting (notifications), but there's probably more out there i haven't encountered. unsure about that commit.
    * that said, individually hunting down parts that could use a shadow in a codebase as large as misskey feels like a tiring job, so not sure on what the best way to approach that would be
* pnpm lint runs out of memory in my laptop

2023-10-30 12:48 UTC, Mar0xy commented
> hide status indicators when they're in an "unknown" state

This mainly was left in by misskey to keep consistency so it's not just like woop all of a sudden the status indicator is not here while on other profiles it is.

> add more shadows

A big issue I see with this is performance on the client as the more CSS Effects need to be rendered (especially on the profile page as it also has css effects for the background images) the slower/laggier it gets.

2023-10-30 12:55 UTC, Mar0xy commented on packages/frontend/src/components/MkDateSeparatedList.vue
> +	border-radius: var(--radius);
Why was this moved out of `*`? it could have stayed in it's original place

2023-10-30 13:05 UTC, ShittyKopper commented on packages/frontend/src/components/MkDateSeparatedList.vue
> +	border-radius: var(--radius);
removing `border-radius: 0` from `*` was from a previous try at making this work. shouldn't be necessary with border-radius being explicitly defined in `MkNotes`

2023-10-30 13:08 UTC, Mar0xy commented
> show a pointer cursor when hovering over clickable parts of notes when "Click to open notes" is enabled

While this is a nice idea on paper it kinda translates weirdly due to the fact that it makes it harder to indicate if someone is hovering over the footer icons, cw button and as well as making the cursor be basically a permanent pointer (which lets be honest  when it comes to the way the pointer looks it has always looked weird/ugly).

2023-10-30 13:30 UTC, ShittyKopper commented
> This mainly was left in by misskey to keep consistency so it's not just like woop all of a sudden the status indicator is not here while on other profiles it is.

:+1:, dropping that commit in this case

> A big issue I see with this is performance on the client as the more CSS Effects need to be rendered (especially on the profile page as it also has css effects for the background images which currently affect the entire site on stable and has already been fixed) the slower/laggier it gets.

true, but imo there needs to be some way to separate things from the background, barely perceptible color changes do not cut it (especially on pages without a background image)

there may be a way to pull it off with borders which should be slightly more resource efficient, i'll have to experiment

> While this is a nice idea on paper it kinda translates weirdly due to the fact that it makes it harder to indicate if someone is hovering over the footer icons, cw button 

right now there is no other indication on what part of a note is clickable and what part isn't. especially on posts with reactions or audio where the empty space next to them do not open the post (or the empty space under the avatar, which in fairness seems to be consistent with masto) 

the footer icons can be solved by giving them a hover color (which i'll may throw in with the next revision of this pr, depends on if my brain's willing to cooperate),  
and the cw button changes background colors which feels reasonable to me (and the cursor doesn't change because the post hitbox is that close to the cw button)

not entirely sure on what you mean by "and as well as making the cursor be basically a permanent pointer (which lets be honest when it comes to the way the pointer looks it has always looked weird/ugly)." though

2023-10-31 12:33 UTC, ShittyKopper commented
revision 2: using a border does seem to look pretty nice, and should be less resource intensive compared to shadows. also snuck in a fix for shadows and transparent avatars in the profile page

![Screenshot 2023-10-31 at 15-29-16 @kopper](https://github.com/transfem-org/Sharkey/assets/106974765/e36674a3-11e5-4b4e-b481-bcc201e8b3a7)
![Screenshot 2023-10-31 at 15-28-29 @kopper](https://github.com/transfem-org/Sharkey/assets/106974765/f62e1e9c-58c5-4711-878c-30b6bc57d241)

2023-10-31 17:15 UTC, ShittyKopper commented
there are a few more changes i'd like to make but they're significantly larger and probably deserve their own individual PRs (if i manage to pull them off, that is). un-drafting this pr

2023-11-01 20:28 UTC, Mar0xy requested changes
As said on Discord the borders don't look good depending on the theme you use and it would probably be good to avoid trying to separate the background and containers for now until a better solution can be found.

2023-11-01 20:48 UTC, ShittyKopper commented
dropped borders & rebased on develop

2023-11-01 22:01 UTC, Mar0xy approved these changes

2023-11-01 22:01 UTC, merged